traits:
  Ruby: true

include:
  - cider-ci/task-components/database/configure.yml
  - cider-ci/task-components/database/delete.yml

scripts:

  create-database:
    body: |
      #!/usr/bin/env bash
      set -eux
      createdb "$DATABASE_NAME"
      psql -d "$DATABASE_NAME" -f db/structure.sql
      DATABASE_NAME="$DATABASE_NAME" ./scripts/restore-seeds

  test:
    start_when:
      database has been created:
        script_key: create-database
