include:
  - cider-ci/task-components/asdf-nodejs.yml

scripts:

  inventory-service-run:
    start_when:
      nodejs is installed:
        script_key: inventory-nodejs-asdf-install
      uberjar has been built:
        script_key: inventory-build-uberjar
      database has been created:
        script_key: create-database
    body: |
      #!/usr/bin/env bash
      set -euo pipefail
      export HTTP_PORT=${LEIHS_INVENTORY_HTTP_PORT}
      cd $LEIHS_INVENTORY_DIR
      mkdir -p $LEIHS_INVENTORY_DIR/tmp
      unset PGPORT
      unset PGUSER
      PGPORT=${PG15PORT} PGUSER=${PG15USER} java \
        -jar leihs-inventory.jar \
        run --pid-file tmp/service.pid

  inventory-service-is-running:
    body: |
      #!/usr/bin/env bash
      set -euo pipefail
      until curl --silent --fail -I -X GET \
        -H 'Accept: application/json' \
        "http://localhost:${LEIHS_INVENTORY_HTTP_PORT}/inventory/status";
        do sleep 1;
      done
    start_when:
      run server is executing:
        script_key: inventory-service-run
        states: [executing]

  test:
    start_when:
      admin service is running:
        script_key: inventory-service-is-running

  shutdown-inventory-service:
    body: |
      #!/usr/bin/env bash
      set -euo pipefail
      cd $LEIHS_INVENTORY_DIR
      export PID=$(cat tmp/service.pid)
      kill $PID
      tail --pid=$PID -f /dev/null
    start_when:
      test is terminal:
        script_key: test
        states: [aborted, defective, passed, failed, skipped]

  delete-database:
    start_when:
      shutdown-inventory-service is in termial state:
        script_key: shutdown-inventory-service
        states: [aborted, defective, passed, failed, skipped]
