# foo
 
pg: &default
  adapter: postgresql
  host: localhost
  port: 5432
  pool: 5
  encoding: unicode
  username: <%= ENV['DB_USER'].presence || ENV['PGUSER'].presence || 'leihs' %>
  password: <%= ENV['DB_PASSWORD'].presence || ENV['PGPASSWORD'].presence || 'leihs' %>
  database: <%= ENV['DB_NAME'].presence || ENV['PGDATABASE'].presence || 'leihs' %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
