- name: rp_maintenance
  include_tasks: rev_prox_maintenance.yml
  when: leihs_inventory == true

- name: rp_off
  include_tasks: rev_prox_disabled.yml
  when: leihs_inventory == false

- name: prepare
  include_tasks: prepare.yml

- name: build
  include_tasks: build.yml
  when: leihs_inventory == true

- name: install jar
  include_tasks: install_jar.yml
  when: leihs_inventory == true

- name: systemd service
  include_tasks: service.yml
  when: leihs_inventory == true

- name: reverse-proxy
  include_tasks: reverse-proxy.yml
  when: leihs_inventory == true
